version: "3.8"
services:
  postgresql_db:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=spreadword_db
    ports:
      - "5432:5432"
    networks:
      - app_net
  user_service:
    build: ./server/user_service
    container_name: user_service
    environment:
      - JWT_SECRET_KEY=43243214fdgwerq
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_NAME=spreadword_db
      - DB_PORT=5432
      - GRPC_PORT=5104
    ports:
      - "8080:8080"
      - "5104:5104"
      - "9080:9080"
    depends_on:
      - postgresql_db
      - rabbit_mq
    networks:
      - app_net
    volumes:
      - ./server/user_service:/app
  post_service:
    build: ./server/post_service
    container_name: post_service
    environment:
      - GRPC_PORT=5104
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_NAME=spreadword_db
      - DB_PORT=5432
    ports:
      - "8081:8081"
      - "9081:9081"
    depends_on:
      - postgresql_db
      - user_service
    networks:
      - app_net
    volumes:
      - ./server/post_service:/app
  photo_service:
    build: ./server/photo_service
    container_name: photo_service
    volumes:
      - ./server/photo_service:/app
    depends_on:
      - post_service
      - rabbit_mq
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_NAME=spreadword_db
      - DB_PORT=5432
    networks:
      - app_net
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
  grafana:
    image: grafana/grafana-oss:9.4.3
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
  rabbit_mq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"


networks:
  app_net:
    driver: bridge
volumes:
  grafana-data:
